// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmdYkEWS0CytQyXggK_c813lO7sUWN1xE',
    appId: '1:860506144525:web:e581707a7e7a77fd57fa44',
    messagingSenderId: '860506144525',
    projectId: 'luxe-online-store',
    authDomain: 'luxe-online-store.firebaseapp.com',
    storageBucket: 'luxe-online-store.firebasestorage.app',
    measurementId: 'G-KTTNR48MXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKtcDd1a_VOBZbnctw-oUsBtIENxL6r8E',
    appId: '1:860506144525:android:08de3eef5cbe0be957fa44',
    messagingSenderId: '860506144525',
    projectId: 'luxe-online-store',
    storageBucket: 'luxe-online-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Gib2xmqIDeA6Iidxf4fo82PooWudQ3o',
    appId: '1:860506144525:ios:49c7320cd7f00bba57fa44',
    messagingSenderId: '860506144525',
    projectId: 'luxe-online-store',
    storageBucket: 'luxe-online-store.firebasestorage.app',
    iosClientId: '860506144525-m10967ha2mu3msl1u66k176tb8a83ker.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0Gib2xmqIDeA6Iidxf4fo82PooWudQ3o',
    appId: '1:860506144525:ios:49c7320cd7f00bba57fa44',
    messagingSenderId: '860506144525',
    projectId: 'luxe-online-store',
    storageBucket: 'luxe-online-store.firebasestorage.app',
    iosClientId: '860506144525-m10967ha2mu3msl1u66k176tb8a83ker.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmdYkEWS0CytQyXggK_c813lO7sUWN1xE',
    appId: '1:860506144525:web:e69cf4a3e6e915df57fa44',
    messagingSenderId: '860506144525',
    projectId: 'luxe-online-store',
    authDomain: 'luxe-online-store.firebaseapp.com',
    storageBucket: 'luxe-online-store.firebasestorage.app',
    measurementId: 'G-R4JJNJ0VEE',
  );

}